#!/usr/bin/env node
/** Writes scripts/patches/{locale}.json from embedded manual strings. */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, "patches");

/** @param {string} u unit for years e.g. "J.", "ans" */
function yrs(u) {
  return {
    about_skill_1_years: `7+ ${u}`,
    about_skill_2_years: `7+ ${u}`,
    about_skill_3_years: `9+ ${u}`,
    about_skill_4_years: `4+ ${u}`,
    about_skill_5_years: `5+ ${u}`,
    about_skill_6_years: `6+ ${u}`,
    about_skill_7_years: `5+ ${u}`,
    about_skill_8_years: `4+ ${u}`,
    about_skill_9_years: `4+ ${u}`,
    about_skill_10_years: `2+ ${u}`,
  };
}

/** @typedef {{ title: string, summary: string, email: string, phone: string, passport: string, relocate: string, relocateVal: string, p1: string, p2: string, p3: string, p4: string, resumeUpdated: string, edu: object, hi: string[], jobs: string[], yearUnit: string }} LocaleBlock */

/** @type {Record<string, LocaleBlock>} */
const L = {
  de: {
    yearUnit: "J.",
    title: "Senior Full-Stack-Ingenieur",
    summary:
      "Senior Full-Stack-Ingenieur mit über 9 Jahren Erfahrung im Aufbau unternehmenstauglicher Cloud-nativer Anwendungen mit React.js, Node.js und TypeScript. Experte für Microservices, Systemdesign, Serverless (AWS Lambda, Azure Functions) und KI-gestützte Entwicklung. High-Impact-Lösungen für Banking (Northern Trust), Pharma (Eli Lilly) und Regierung (VAE) mit 99,9 % Verfügbarkeit. Bewährte CI/CD-Automatisierung, skalierbare Architektur und Agile Delivery.",
    email: "E-Mail:",
    phone: "Telefon:",
    passport: "Verfügbar (gültig bis 2033)",
    relocate: "Umzug:",
    relocateVal: "Offen für VAE, UK, Europa",
    p1: "Stets neugierig, neue Technologien und Muster zu lernen",
    p2: "Starker Team Lead — Mentoring, Code Reviews und Delivery-Verantwortung",
    p3: "Klare Kommunikation mit technischen und nicht-technischen Stakeholdern",
    p4: "Erfahrung in Banking, Pharma und Regierung (USA, VAE, Indien)",
    resumeUpdated: "Zuletzt aktualisiert: 13. Sep. 2026",
    edu: {
      resume_edu_btech_degree: "Bachelor of Technology (B.Tech)",
      resume_edu_btech_field: "Elektrotechnik und Kommunikationstechnik",
      resume_edu_btech_school:
        "Biju Patnaik University of Technology (BPUT), Bhubaneswar",
      resume_edu_hsc_degree: "Höhere Sekundarstufe (ISC)",
      resume_edu_hsc_field: "Naturwissenschaften und Mathematik",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "High School (ICSE)",
      resume_edu_icse_field: "Naturwissenschaften und Mathematik",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "Manuelle Dokumentenverarbeitung für Northern Trust um 60 % reduziert (10K+ Docs/Tag)",
      "20+ Medium-Artikel mit Reichweite 10K+ Entwickler",
    ],
    jobs: [
      "Kanban-Anwendung für Kupferlösungs-Geschäftsworkflows.",
      "KI-gestützte Dokumentendigitalisierung (NT Digitizer) — 10K+ Finanzdokumente/Tag, 95 %+ OCR.",
      "Eli Lilly IBU Sales Analytics — Tagesverkäufe für Indien und Taiwan.",
      "Digitale Regierungsdienste VAE (TAMM) — React/TypeScript, Camunda BPMN.",
      "Full-Stack-Produkte: E-Commerce, OAuth, E-Learning.",
      "Crowdfunding- und E-Commerce-Plattform mit Laravel und AngularJS.",
    ],
  },
  fr: {
    yearUnit: "ans",
    title: "Ingénieur Full Stack senior",
    summary:
      "Ingénieur Full Stack senior avec plus de 9 ans d'expérience dans la création d'applications cloud natives de niveau entreprise avec React.js, Node.js et TypeScript. Expert en microservices, conception système, serverless (AWS Lambda, Azure Functions) et développement assisté par l'IA. Solutions à fort impact pour la banque (Northern Trust), la pharma (Eli Lilly) et le gouvernement (EAU) avec 99,9 % de disponibilité. CI/CD, architecture scalable et livraison Agile.",
    email: "E-mail :",
    phone: "Téléphone :",
    passport: "Disponible (exp. 2033)",
    relocate: "Mobilité :",
    relocateVal: "Ouvert EAU, Royaume-Uni, Europe",
    p1: "Toujours curieux d'apprendre de nouvelles technologies et patterns",
    p2: "Team lead solide — mentorat, revues de code et responsabilité de livraison",
    p3: "Communication claire avec parties prenantes techniques et non techniques",
    p4: "Expérience banque, pharma et secteur public (États-Unis, EAU, Inde)",
    resumeUpdated: "Dernière mise à jour : 13 sept. 2026",
    edu: {
      resume_edu_btech_degree: "Licence en technologie (B.Tech)",
      resume_edu_btech_field: "Électronique et télécommunications",
      resume_edu_btech_school:
        "Université de technologie Biju Patnaik (BPUT), Bhubaneswar",
      resume_edu_hsc_degree: "Secondaire supérieur (ISC)",
      resume_edu_hsc_field: "Sciences et mathématiques",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "Lycée (ICSE)",
      resume_edu_icse_field: "Sciences et mathématiques",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "Prix EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "Réduction de 60 % du traitement manuel de documents pour Northern Trust (10K+ docs/jour)",
      "20+ articles Medium touchant 10K+ développeurs",
    ],
    jobs: [
      "Application Kanban adaptée aux flux métier cuivre.",
      "Plateforme de numérisation IA (NT Digitizer) — 10K+ documents financiers/jour, OCR 95 %+.",
      "Eli Lilly IBU Sales Analytics — ventes quotidiennes Inde et Taïwan.",
      "Services numériques gouvernementaux EAU (TAMM) — React/TypeScript, Camunda BPMN.",
      "Produits full stack : e-commerce, OAuth, e-learning.",
      "Plateforme crowdfunding et e-commerce Laravel / AngularJS.",
    ],
  },
  es: {
    yearUnit: "años",
    title: "Ingeniero Full Stack senior",
    summary:
      "Ingeniero Full Stack senior con más de 9 años creando aplicaciones cloud nativas de nivel empresarial con React.js, Node.js y TypeScript. Experto en microservicios, diseño de sistemas, serverless (AWS Lambda, Azure Functions) y desarrollo asistido por IA. Soluciones de alto impacto para banca (Northern Trust), farmacéutica (Eli Lilly) y gobierno (EAU) con 99,9 % de uptime. CI/CD, arquitectura escalable y entrega Agile.",
    email: "Correo:",
    phone: "Teléfono:",
    passport: "Disponible (exp. 2033)",
    relocate: "Reubicación:",
    relocateVal: "Abierto a EAU, Reino Unido, Europa",
    p1: "Siempre con ganas de aprender nuevas tecnologías y patrones",
    p2: "Líder de equipo sólido — mentoría, revisiones de código y entrega",
    p3: "Comunicación clara con stakeholders técnicos y de negocio",
    p4: "Experiencia en banca, farmacéutica y gobierno (EE. UU., EAU, India)",
    resumeUpdated: "Última actualización: 13 sep. 2026",
    edu: {
      resume_edu_btech_degree: "Grado en tecnología (B.Tech)",
      resume_edu_btech_field: "Ingeniería electrónica y de comunicaciones",
      resume_edu_btech_school:
        "Universidad de tecnología Biju Patnaik (BPUT), Bhubaneswar",
      resume_edu_hsc_degree: "Bachillerato superior (ISC)",
      resume_edu_hsc_field: "Ciencias y matemáticas",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "Escuela secundaria (ICSE)",
      resume_edu_icse_field: "Ciencias y matemáticas",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "Premio EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "Reducción del 60 % del procesamiento manual para Northern Trust (10K+ docs/día)",
      "20+ artículos en Medium llegando a 10K+ desarrolladores",
    ],
    jobs: [
      "Aplicación Kanban para flujos de negocio de soluciones de cobre.",
      "Plataforma de digitalización con IA (NT Digitizer) — 10K+ documentos/día, OCR 95 %+.",
      "Eli Lilly IBU Sales Analytics — ventas diarias India y Taiwán.",
      "Servicios digitales gubernamentales EAU (TAMM) — React/TypeScript, Camunda BPMN.",
      "Productos full stack: e-commerce, OAuth, e-learning.",
      "Plataforma crowdfunding y e-commerce con Laravel y AngularJS.",
    ],
  },
  pt: {
    yearUnit: "anos",
    title: "Engenheiro Full Stack sénior",
    summary:
      "Engenheiro Full Stack sénior com mais de 9 anos a criar aplicações cloud-native de nível empresarial com React.js, Node.js e TypeScript. Especialista em microserviços, design de sistemas, serverless (AWS Lambda, Azure Functions) e desenvolvimento assistido por IA. Soluções de alto impacto para banca (Northern Trust), farmacêutica (Eli Lilly) e governo (EAU) com 99,9% de uptime.",
    email: "E-mail:",
    phone: "Telefone:",
    passport: "Disponível (exp. 2033)",
    relocate: "Relocalização:",
    relocateVal: "Aberto a EAU, Reino Unido, Europa",
    p1: "Sempre curioso para aprender novas tecnologias e padrões",
    p2: "Líder de equipa forte — mentoria, revisões de código e entrega",
    p3: "Comunicação clara com stakeholders técnicos e não técnicos",
    p4: "Experiência em banca, farmacêutica e governo (EUA, EAU, Índia)",
    resumeUpdated: "Última atualização: 13 set. 2026",
    edu: {
      resume_edu_btech_degree: "Licenciatura em tecnologia (B.Tech)",
      resume_edu_btech_field: "Engenharia eletrónica e de comunicações",
      resume_edu_btech_school: "Universidade Biju Patnaik (BPUT), Bhubaneswar",
      resume_edu_hsc_degree: "Ensino secundário superior (ISC)",
      resume_edu_hsc_field: "Ciências e matemática",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "Escola secundária (ICSE)",
      resume_edu_icse_field: "Ciências e matemática",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "Prémio EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "Redução de 60% do processamento manual para Northern Trust (10K+ docs/dia)",
      "20+ artigos Medium com 10K+ developers",
    ],
    jobs: [
      "Aplicação Kanban para fluxos de negócio de soluções de cobre.",
      "Plataforma de digitalização com IA (NT Digitizer) — 10K+ documentos/dia.",
      "Eli Lilly IBU Sales Analytics — vendas diárias Índia e Taiwan.",
      "Serviços digitais governamentais EAU (TAMM) — React/TypeScript, Camunda.",
      "Produtos full stack: e-commerce, OAuth, e-learning.",
      "Crowdfunding e e-commerce com Laravel e AngularJS.",
    ],
  },
  it: {
    yearUnit: "anni",
    title: "Ingegnere Full Stack senior",
    summary:
      "Ingegnere Full Stack senior con oltre 9 anni di esperienza nello sviluppo di applicazioni cloud-native enterprise con React.js, Node.js e TypeScript. Esperto in microservizi, system design, serverless (AWS Lambda, Azure Functions) e sviluppo assistito dall'IA. Soluzioni ad alto impatto per banking (Northern Trust), pharma (Eli Lilly) e governo (EAU) con uptime 99,9%.",
    email: "Email:",
    phone: "Telefono:",
    passport: "Disponibile (scad. 2033)",
    relocate: "Trasferimento:",
    relocateVal: "Aperto a EAU, UK, Europa",
    p1: "Sempre curioso di imparare nuove tecnologie e pattern",
    p2: "Team lead forte — mentoring, code review e ownership della delivery",
    p3: "Comunicazione chiara con stakeholder tecnici e non tecnici",
    p4: "Esperienza banking, pharma e governo (USA, EAU, India)",
    resumeUpdated: "Ultimo aggiornamento: 13 set 2026",
    edu: {
      resume_edu_btech_degree: "Laurea in tecnologia (B.Tech)",
      resume_edu_btech_field: "Ingegneria elettronica e delle comunicazioni",
      resume_edu_btech_school: "Biju Patnaik University (BPUT), Bhubaneswar",
      resume_edu_hsc_degree: "Scuola superiore (ISC)",
      resume_edu_hsc_field: "Scienze e matematica",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "Scuola media superiore (ICSE)",
      resume_edu_icse_field: "Scienze e matematica",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "Riduzione del 60% dell'elaborazione manuale per Northern Trust (10K+ doc/giorno)",
      "20+ articoli Medium per 10K+ developer",
    ],
    jobs: [
      "App Kanban per workflow copper-solutions.",
      "Piattaforma digitalizzazione IA (NT Digitizer) — 10K+ documenti/giorno.",
      "Eli Lilly IBU Sales Analytics — vendite giornaliere India e Taiwan.",
      "Servizi digitali governo EAU (TAMM) — React/TypeScript, Camunda.",
      "Prodotti full stack: e-commerce, OAuth, e-learning.",
      "Crowdfunding ed e-commerce con Laravel e AngularJS.",
    ],
  },
  nl: {
    yearUnit: "jr",
    title: "Senior Full Stack engineer",
    summary:
      "Senior Full Stack engineer met 9+ jaar ervaring in enterprise cloud-native applicaties met React.js, Node.js en TypeScript. Expert in microservices, systeemontwerp, serverless (AWS Lambda, Azure Functions) en AI-ondersteunde ontwikkeling. High-impact oplossingen voor banking (Northern Trust), pharma (Eli Lilly) en overheid (VAE) met 99,9% uptime.",
    email: "E-mail:",
    phone: "Telefoon:",
    passport: "Beschikbaar (t/m 2033)",
    relocate: "Verhuizing:",
    relocateVal: "Open voor VAE, UK, Europa",
    p1: "Altijd nieuwsgierig naar nieuwe technologieën en patronen",
    p2: "Sterke teamlead — mentoring, code reviews en delivery-eigenaarschap",
    p3: "Duidelijke communicatie met technische en niet-technische stakeholders",
    p4: "Ervaring banking, pharma en overheid (VS, VAE, India)",
    resumeUpdated: "Laatst bijgewerkt: 13 sep 2026",
    edu: {
      resume_edu_btech_degree: "Bachelor of Technology (B.Tech)",
      resume_edu_btech_field: "Elektronica- en communicatietechniek",
      resume_edu_btech_school: "Biju Patnaik University (BPUT), Bhubaneswar",
      resume_edu_hsc_degree: "Hoger secundair (ISC)",
      resume_edu_hsc_field: "Wetenschap en wiskunde",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "Middelbare school (ICSE)",
      resume_edu_icse_field: "Wetenschap en wiskunde",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "60% minder handmatige documentverwerking voor Northern Trust (10K+ docs/dag)",
      "20+ Medium-artikelen bereikend 10K+ developers",
    ],
    jobs: [
      "Kanban-app voor copper-solutions workflows.",
      "AI-documentdigitalisering (NT Digitizer) — 10K+ financiële docs/dag.",
      "Eli Lilly IBU Sales Analytics — dagelijkse verkoop India en Taiwan.",
      "Digitale overheidsdiensten VAE (TAMM) — React/TypeScript, Camunda.",
      "Full-stack producten: e-commerce, OAuth, e-learning.",
      "Crowdfunding- en e-commerceplatform met Laravel en AngularJS.",
    ],
  },
  pl: {
    yearUnit: "lat",
    title: "Starszy inżynier Full Stack",
    summary:
      "Starszy inżynier Full Stack z ponad 9-letnim doświadczeniem w tworzeniu aplikacji chmurowych klasy enterprise w React.js, Node.js i TypeScript. Ekspert microservices, projektowania systemów, serverless (AWS Lambda, Azure Functions) i rozwoju wspomaganego AI. Rozwiązania o dużym wpływie dla bankowości (Northern Trust), farmacji (Eli Lilly) i sektora publicznego (ZEA) z uptime 99,9%.",
    email: "E-mail:",
    phone: "Telefon:",
    passport: "Dostępny (ważny do 2033)",
    relocate: "Relokacja:",
    relocateVal: "Otwarty na ZEA, UK, Europę",
    p1: "Zawsze chętny do nauki nowych technologii i wzorców",
    p2: "Silny lider zespołu — mentoring, code review i odpowiedzialność za delivery",
    p3: "Jasna komunikacja z interesariuszami technicznymi i biznesowymi",
    p4: "Doświadczenie w bankowości, farmacji i administracji (USA, ZEA, Indie)",
    resumeUpdated: "Ostatnia aktualizacja: 13 wrz 2026",
    edu: {
      resume_edu_btech_degree: "Licencjat inżynierii (B.Tech)",
      resume_edu_btech_field: "Elektronika i telekomunikacja",
      resume_edu_btech_school: "Uniwersytet Biju Patnaik (BPUT), Bhubaneswar",
      resume_edu_hsc_degree: "Szkoła średnia (ISC)",
      resume_edu_hsc_field: "Nauki ścisłe i matematyka",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "Szkoła podstawowa (ICSE)",
      resume_edu_icse_field: "Nauki ścisłe i matematyka",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "Nagroda EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "60% mniej ręcznego przetwarzania dokumentów dla Northern Trust (10K+ docs/dzień)",
      "20+ artykułów Medium — 10K+ developerów",
    ],
    jobs: [
      "Aplikacja Kanban dla workflow copper-solutions.",
      "Platforma digitalizacji AI (NT Digitizer) — 10K+ dokumentów/dzień.",
      "Eli Lilly IBU Sales Analytics — sprzedaż dzienna Indie i Tajwan.",
      "Cyfrowe usługi rządowe ZEA (TAMM) — React/TypeScript, Camunda.",
      "Produkty full stack: e-commerce, OAuth, e-learning.",
      "Crowdfunding i e-commerce z Laravel i AngularJS.",
    ],
  },
  ru: {
    yearUnit: "лет",
    title: "Старший Full Stack инженер",
    summary:
      "Старший Full Stack инженер с более чем 9-летним опытом создания облачных enterprise-приложений на React.js, Node.js и TypeScript. Эксперт в microservices, проектировании систем, serverless (AWS Lambda, Azure Functions) и разработке с ИИ. Решения для банков (Northern Trust), фармы (Eli Lilly) и госсектора (ОАЭ) с uptime 99,9%.",
    email: "Email:",
    phone: "Телефон:",
    passport: "Доступен (до 2033)",
    relocate: "Переезд:",
    relocateVal: "Открыт к ОАЭ, UK, Европе",
    p1: "Всегда стремлюсь изучать новые технологии и паттерны",
    p2: "Сильный тимлид — менторство, code review и ответственность за delivery",
    p3: "Чёткая коммуникация с техническими и нетехническими stakeholders",
    p4: "Опыт в банкинге, фарме и госсекторе (США, ОАЭ, Индия)",
    resumeUpdated: "Обновлено: 13 сен 2026",
    edu: {
      resume_edu_btech_degree: "Бакалавр технологий (B.Tech)",
      resume_edu_btech_field: "Электроника и связь",
      resume_edu_btech_school: "Университет Biju Patnaik (BPUT), Бhubaneswar",
      resume_edu_hsc_degree: "Среднее образование (ISC)",
      resume_edu_hsc_field: "Науки и математика",
      resume_edu_hsc_school: "St. Patrick's H.S. School, Asansol",
      resume_edu_icse_degree: "Школа (ICSE)",
      resume_edu_icse_field: "Науки и математика",
      resume_edu_icse_school: "St. Patrick's H.S. School, Asansol",
    },
    hi: [
      "EY Client Extraordinaire (2024, 2025) · EY Kudos (2023) · TCS Gems (2022)",
      "Сокращение ручной обработки документов на 60% для Northern Trust (10K+ docs/день)",
      "20+ статей Medium — 10K+ разработчиков",
    ],
    jobs: [
      "Kanban-приложение для copper-solutions workflows.",
      "Платформа оцифровки с ИИ (NT Digitizer) — 10K+ документов/день.",
      "Eli Lilly IBU Sales Analytics — ежедневные продажи Индия и Тайвань.",
      "Цифровые госуслуги ОАЭ (TAMM) — React/TypeScript, Camunda.",
      "Full stack: e-commerce, OAuth, e-learning.",
      "Краудфандинг и e-commerce на Laravel и AngularJS.",
    ],
  },
};

function blockToPatch(code, b) {
  return {
    about_page_title: b.title,
    about_page_employer: "@Molex , Bangalore, India",
    about_page_org: "JavaScript · React · Node · TypeScript · Cloud",
    about_page_summary: b.summary,
    about_meta_email: b.email,
    about_meta_phone: b.phone,
    about_meta_passport_val: b.passport,
    about_meta_relocate: b.relocate,
    about_meta_relocate_val: b.relocateVal,
    about_personal_1: b.p1,
    about_personal_2: b.p2,
    about_personal_3: b.p3,
    about_personal_4: b.p4,
    resume_updated: b.resumeUpdated,
    ...b.edu,
    resume_highlight_1: b.hi[0],
    resume_highlight_2: b.hi[1],
    resume_highlight_3: b.hi[2],
    resume_job_molex_summary: b.jobs[0],
    resume_job_ey_summary: b.jobs[1],
    resume_job_tcs_summary: b.jobs[2],
    resume_job_xebia_summary: b.jobs[3],
    resume_job_shadan_summary: b.jobs[4],
    resume_job_fundlr_summary: b.jobs[5],
    ...yrs(b.yearUnit),
  };
}

fs.mkdirSync(OUT, { recursive: true });
for (const [code, block] of Object.entries(L)) {
  fs.writeFileSync(
    path.join(OUT, `${code}.json`),
    JSON.stringify(blockToPatch(code, block), null, 2) + "\n",
  );
  console.log("wrote", code);
}
